/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestingRouteImport } from './routes/_authenticated/testing'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedProjectStatusRouteImport } from './routes/_authenticated/project-status'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated/playlists'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedFutureRouteImport } from './routes/_authenticated/future'
import { Route as AuthenticatedDocumentationRouteImport } from './routes/_authenticated/documentation'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDesktopRouteImport } from './routes/_authenticated/desktop'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedCommandsRouteImport } from './routes/_authenticated/commands'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedBroadcastsRouteImport } from './routes/_authenticated/broadcasts'
import { Route as AuthenticatedDesktopIndexRouteImport } from './routes/_authenticated/desktop.index'
import { Route as AuthenticatedDevicesDeviceIdRouteImport } from './routes/_authenticated/devices.$deviceId'
import { Route as AuthenticatedDesktopMediaRouteImport } from './routes/_authenticated/desktop.media'
import { Route as AuthenticatedDesktopLiveControlRouteImport } from './routes/_authenticated/desktop.live-control'
import { Route as AuthenticatedDesktopDevicesRouteImport } from './routes/_authenticated/desktop.devices'
import { Route as AuthenticatedBroadcastsBroadcastIdRouteImport } from './routes/_authenticated/broadcasts.$broadcastId'
import { Route as ApiPublicDevicesRegisterRouteImport } from './routes/api/public/devices/register'
import { Route as ApiPublicDevicesPairRouteImport } from './routes/api/public/devices/pair'
import { Route as ApiPublicDevicesHeartbeatRouteImport } from './routes/api/public/devices/heartbeat'
import { Route as ApiPublicDevicesAckRouteImport } from './routes/api/public/devices/ack'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestingRoute = AuthenticatedTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectStatusRoute =
  AuthenticatedProjectStatusRouteImport.update({
    id: '/project-status',
    path: '/project-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFutureRoute = AuthenticatedFutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentationRoute =
  AuthenticatedDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesktopRoute = AuthenticatedDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandsRoute = AuthenticatedCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroadcastsRoute = AuthenticatedBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesktopIndexRoute =
  AuthenticatedDesktopIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDesktopRoute,
  } as any)
const AuthenticatedDevicesDeviceIdRoute =
  AuthenticatedDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => AuthenticatedDevicesRoute,
  } as any)
const AuthenticatedDesktopMediaRoute =
  AuthenticatedDesktopMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedDesktopRoute,
  } as any)
const AuthenticatedDesktopLiveControlRoute =
  AuthenticatedDesktopLiveControlRouteImport.update({
    id: '/live-control',
    path: '/live-control',
    getParentRoute: () => AuthenticatedDesktopRoute,
  } as any)
const AuthenticatedDesktopDevicesRoute =
  AuthenticatedDesktopDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedDesktopRoute,
  } as any)
const AuthenticatedBroadcastsBroadcastIdRoute =
  AuthenticatedBroadcastsBroadcastIdRouteImport.update({
    id: '/$broadcastId',
    path: '/$broadcastId',
    getParentRoute: () => AuthenticatedBroadcastsRoute,
  } as any)
const ApiPublicDevicesRegisterRoute =
  ApiPublicDevicesRegisterRouteImport.update({
    id: '/api/public/devices/register',
    path: '/api/public/devices/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesPairRoute = ApiPublicDevicesPairRouteImport.update({
  id: '/api/public/devices/pair',
  path: '/api/public/devices/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesHeartbeatRoute =
  ApiPublicDevicesHeartbeatRouteImport.update({
    id: '/api/public/devices/heartbeat',
    path: '/api/public/devices/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesAckRoute = ApiPublicDevicesAckRouteImport.update({
  id: '/api/public/devices/ack',
  path: '/api/public/devices/ack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRouteWithChildren
  '/client': typeof AuthenticatedClientRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desktop': typeof AuthenticatedDesktopRouteWithChildren
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/future': typeof AuthenticatedFutureRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/project-status': typeof AuthenticatedProjectStatusRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/testing': typeof AuthenticatedTestingRoute
  '/broadcasts/$broadcastId': typeof AuthenticatedBroadcastsBroadcastIdRoute
  '/desktop/devices': typeof AuthenticatedDesktopDevicesRoute
  '/desktop/live-control': typeof AuthenticatedDesktopLiveControlRoute
  '/desktop/media': typeof AuthenticatedDesktopMediaRoute
  '/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/desktop/': typeof AuthenticatedDesktopIndexRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/pair': typeof ApiPublicDevicesPairRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRouteWithChildren
  '/client': typeof AuthenticatedClientRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/future': typeof AuthenticatedFutureRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/project-status': typeof AuthenticatedProjectStatusRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/testing': typeof AuthenticatedTestingRoute
  '/broadcasts/$broadcastId': typeof AuthenticatedBroadcastsBroadcastIdRoute
  '/desktop/devices': typeof AuthenticatedDesktopDevicesRoute
  '/desktop/live-control': typeof AuthenticatedDesktopLiveControlRoute
  '/desktop/media': typeof AuthenticatedDesktopMediaRoute
  '/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/desktop': typeof AuthenticatedDesktopIndexRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/pair': typeof ApiPublicDevicesPairRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/broadcasts': typeof AuthenticatedBroadcastsRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRoute
  '/_authenticated/commands': typeof AuthenticatedCommandsRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desktop': typeof AuthenticatedDesktopRouteWithChildren
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/_authenticated/documentation': typeof AuthenticatedDocumentationRoute
  '/_authenticated/future': typeof AuthenticatedFutureRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/project-status': typeof AuthenticatedProjectStatusRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
  '/_authenticated/testing': typeof AuthenticatedTestingRoute
  '/_authenticated/broadcasts/$broadcastId': typeof AuthenticatedBroadcastsBroadcastIdRoute
  '/_authenticated/desktop/devices': typeof AuthenticatedDesktopDevicesRoute
  '/_authenticated/desktop/live-control': typeof AuthenticatedDesktopLiveControlRoute
  '/_authenticated/desktop/media': typeof AuthenticatedDesktopMediaRoute
  '/_authenticated/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdRoute
  '/_authenticated/desktop/': typeof AuthenticatedDesktopIndexRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/pair': typeof ApiPublicDevicesPairRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/broadcasts'
    | '/client'
    | '/commands'
    | '/content'
    | '/dashboard'
    | '/desktop'
    | '/devices'
    | '/documentation'
    | '/future'
    | '/groups'
    | '/playlists'
    | '/project-status'
    | '/roadmap'
    | '/schedules'
    | '/simulator'
    | '/testing'
    | '/broadcasts/$broadcastId'
    | '/desktop/devices'
    | '/desktop/live-control'
    | '/desktop/media'
    | '/devices/$deviceId'
    | '/desktop/'
    | '/api/public/devices/ack'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/pair'
    | '/api/public/devices/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/broadcasts'
    | '/client'
    | '/commands'
    | '/content'
    | '/dashboard'
    | '/devices'
    | '/documentation'
    | '/future'
    | '/groups'
    | '/playlists'
    | '/project-status'
    | '/roadmap'
    | '/schedules'
    | '/simulator'
    | '/testing'
    | '/broadcasts/$broadcastId'
    | '/desktop/devices'
    | '/desktop/live-control'
    | '/desktop/media'
    | '/devices/$deviceId'
    | '/desktop'
    | '/api/public/devices/ack'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/pair'
    | '/api/public/devices/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/broadcasts'
    | '/_authenticated/client'
    | '/_authenticated/commands'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/desktop'
    | '/_authenticated/devices'
    | '/_authenticated/documentation'
    | '/_authenticated/future'
    | '/_authenticated/groups'
    | '/_authenticated/playlists'
    | '/_authenticated/project-status'
    | '/_authenticated/roadmap'
    | '/_authenticated/schedules'
    | '/_authenticated/simulator'
    | '/_authenticated/testing'
    | '/_authenticated/broadcasts/$broadcastId'
    | '/_authenticated/desktop/devices'
    | '/_authenticated/desktop/live-control'
    | '/_authenticated/desktop/media'
    | '/_authenticated/devices/$deviceId'
    | '/_authenticated/desktop/'
    | '/api/public/devices/ack'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/pair'
    | '/api/public/devices/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDevicesAckRoute: typeof ApiPublicDevicesAckRoute
  ApiPublicDevicesHeartbeatRoute: typeof ApiPublicDevicesHeartbeatRoute
  ApiPublicDevicesPairRoute: typeof ApiPublicDevicesPairRoute
  ApiPublicDevicesRegisterRoute: typeof ApiPublicDevicesRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/testing': {
      id: '/_authenticated/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof AuthenticatedTestingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-status': {
      id: '/_authenticated/project-status'
      path: '/project-status'
      fullPath: '/project-status'
      preLoaderRoute: typeof AuthenticatedProjectStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/future': {
      id: '/_authenticated/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof AuthenticatedFutureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentation': {
      id: '/_authenticated/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AuthenticatedDocumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desktop': {
      id: '/_authenticated/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof AuthenticatedDesktopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commands': {
      id: '/_authenticated/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AuthenticatedCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcasts': {
      id: '/_authenticated/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AuthenticatedBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desktop/': {
      id: '/_authenticated/desktop/'
      path: '/'
      fullPath: '/desktop/'
      preLoaderRoute: typeof AuthenticatedDesktopIndexRouteImport
      parentRoute: typeof AuthenticatedDesktopRoute
    }
    '/_authenticated/devices/$deviceId': {
      id: '/_authenticated/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
    '/_authenticated/desktop/media': {
      id: '/_authenticated/desktop/media'
      path: '/media'
      fullPath: '/desktop/media'
      preLoaderRoute: typeof AuthenticatedDesktopMediaRouteImport
      parentRoute: typeof AuthenticatedDesktopRoute
    }
    '/_authenticated/desktop/live-control': {
      id: '/_authenticated/desktop/live-control'
      path: '/live-control'
      fullPath: '/desktop/live-control'
      preLoaderRoute: typeof AuthenticatedDesktopLiveControlRouteImport
      parentRoute: typeof AuthenticatedDesktopRoute
    }
    '/_authenticated/desktop/devices': {
      id: '/_authenticated/desktop/devices'
      path: '/devices'
      fullPath: '/desktop/devices'
      preLoaderRoute: typeof AuthenticatedDesktopDevicesRouteImport
      parentRoute: typeof AuthenticatedDesktopRoute
    }
    '/_authenticated/broadcasts/$broadcastId': {
      id: '/_authenticated/broadcasts/$broadcastId'
      path: '/$broadcastId'
      fullPath: '/broadcasts/$broadcastId'
      preLoaderRoute: typeof AuthenticatedBroadcastsBroadcastIdRouteImport
      parentRoute: typeof AuthenticatedBroadcastsRoute
    }
    '/api/public/devices/register': {
      id: '/api/public/devices/register'
      path: '/api/public/devices/register'
      fullPath: '/api/public/devices/register'
      preLoaderRoute: typeof ApiPublicDevicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/pair': {
      id: '/api/public/devices/pair'
      path: '/api/public/devices/pair'
      fullPath: '/api/public/devices/pair'
      preLoaderRoute: typeof ApiPublicDevicesPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/heartbeat': {
      id: '/api/public/devices/heartbeat'
      path: '/api/public/devices/heartbeat'
      fullPath: '/api/public/devices/heartbeat'
      preLoaderRoute: typeof ApiPublicDevicesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/ack': {
      id: '/api/public/devices/ack'
      path: '/api/public/devices/ack'
      fullPath: '/api/public/devices/ack'
      preLoaderRoute: typeof ApiPublicDevicesAckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBroadcastsRouteChildren {
  AuthenticatedBroadcastsBroadcastIdRoute: typeof AuthenticatedBroadcastsBroadcastIdRoute
}

const AuthenticatedBroadcastsRouteChildren: AuthenticatedBroadcastsRouteChildren =
  {
    AuthenticatedBroadcastsBroadcastIdRoute:
      AuthenticatedBroadcastsBroadcastIdRoute,
  }

const AuthenticatedBroadcastsRouteWithChildren =
  AuthenticatedBroadcastsRoute._addFileChildren(
    AuthenticatedBroadcastsRouteChildren,
  )

interface AuthenticatedDesktopRouteChildren {
  AuthenticatedDesktopDevicesRoute: typeof AuthenticatedDesktopDevicesRoute
  AuthenticatedDesktopLiveControlRoute: typeof AuthenticatedDesktopLiveControlRoute
  AuthenticatedDesktopMediaRoute: typeof AuthenticatedDesktopMediaRoute
  AuthenticatedDesktopIndexRoute: typeof AuthenticatedDesktopIndexRoute
}

const AuthenticatedDesktopRouteChildren: AuthenticatedDesktopRouteChildren = {
  AuthenticatedDesktopDevicesRoute: AuthenticatedDesktopDevicesRoute,
  AuthenticatedDesktopLiveControlRoute: AuthenticatedDesktopLiveControlRoute,
  AuthenticatedDesktopMediaRoute: AuthenticatedDesktopMediaRoute,
  AuthenticatedDesktopIndexRoute: AuthenticatedDesktopIndexRoute,
}

const AuthenticatedDesktopRouteWithChildren =
  AuthenticatedDesktopRoute._addFileChildren(AuthenticatedDesktopRouteChildren)

interface AuthenticatedDevicesRouteChildren {
  AuthenticatedDevicesDeviceIdRoute: typeof AuthenticatedDevicesDeviceIdRoute
}

const AuthenticatedDevicesRouteChildren: AuthenticatedDevicesRouteChildren = {
  AuthenticatedDevicesDeviceIdRoute: AuthenticatedDevicesDeviceIdRoute,
}

const AuthenticatedDevicesRouteWithChildren =
  AuthenticatedDevicesRoute._addFileChildren(AuthenticatedDevicesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBroadcastsRoute: typeof AuthenticatedBroadcastsRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRoute
  AuthenticatedCommandsRoute: typeof AuthenticatedCommandsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesktopRoute: typeof AuthenticatedDesktopRouteWithChildren
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRouteWithChildren
  AuthenticatedDocumentationRoute: typeof AuthenticatedDocumentationRoute
  AuthenticatedFutureRoute: typeof AuthenticatedFutureRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedProjectStatusRoute: typeof AuthenticatedProjectStatusRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
  AuthenticatedTestingRoute: typeof AuthenticatedTestingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBroadcastsRoute: AuthenticatedBroadcastsRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRoute,
  AuthenticatedCommandsRoute: AuthenticatedCommandsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesktopRoute: AuthenticatedDesktopRouteWithChildren,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRouteWithChildren,
  AuthenticatedDocumentationRoute: AuthenticatedDocumentationRoute,
  AuthenticatedFutureRoute: AuthenticatedFutureRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedProjectStatusRoute: AuthenticatedProjectStatusRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
  AuthenticatedTestingRoute: AuthenticatedTestingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDevicesAckRoute: ApiPublicDevicesAckRoute,
  ApiPublicDevicesHeartbeatRoute: ApiPublicDevicesHeartbeatRoute,
  ApiPublicDevicesPairRoute: ApiPublicDevicesPairRoute,
  ApiPublicDevicesRegisterRoute: ApiPublicDevicesRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
